input {
  tcp {
    port => 5000
    codec => json_lines
  }
  udp {
    port => 5000
    codec => json_lines
  }
}

filter {
  if [logger_name] {
    mutate {
      add_field => { "service" => "task-manager" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "task-manager-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
